import localFont from 'next/font/local';
import Header from '@/components/Layout/Header';
import Footer from '@/components/Layout/Footer';
import PokeProvider from './PokeProvider';

import '../styles/globals.css';

const moderustic = localFont({
	src: [
		{
			path: './fonts/moderustic-regular.ttf',
			weight: '400',
			style: 'normal',
		},
		{
			path: './fonts/moderustic-medium.ttf',
			weight: '500',
			style: 'normal',
		},
		{
			path: './fonts/moderustic-semibold.ttf',
			weight: '600',
			style: 'normal',
		},
		{
			path: './fonts/moderustic-bold.ttf',
			weight: '700',
			style: 'normal',
		},
	],
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={moderustic.className}>
				<Header />
				<PokeProvider>
					<main id='content' className='min-h-screen'>
						{children}
					</main>
				</PokeProvider>
				<Footer />
			</body>
		</html>
	);
}
